config/routes.rb
Rails.application.routes.draw do
  root 'incoming_events#index'

  get "password_resets/new"
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions
  resources :users
  resources :password_resets
  resources :remote_sides

  resources :incoming_events
  resources :expected_events

  resources :alarms do
    get :run, :on => :member
  end

  post '/' => 'incoming_events#create'

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  # validations
  #
  #

  validates :password, length: { minimum: 5 }, if: lambda { |m| m.password.present? }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create },
                              presence: true, uniqueness: true

  # callbacks
  #
  #

  before_create { generate_token(:auth_token) }

  # instance methods
  #
  #

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.now.utc
    save!(validate: false)
    UserMailer.password_reset(self).deliver_later
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :sort_column, :sort_direction
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @users = User.order(sort_column + ' ' + sort_direction).page(params[:page]).per(10)
    else
      redirect_to incoming_events_path, alert: "Not authorized"
    end
  end

  def new
    if current_user.admin?
      @user = User.new
    else
      redirect_to user_path(current_user), alert: "Not authorized"
    end
  end

  def create
    if current_user.admin?
      @user = User.new(user_params)

      # OPTIMIZE: Move this into the User model
      if params[:send_invitation] == '1'
        @user.password = @user.password_confirmation = SecureRandom.hex(16)
        @user.generate_token(:password_reset_token)
        @user.password_reset_sent_at = Time.now.utc
      end

      if @user.save
        redirect_to users_path
        if params[:send_invitation] == '1'
          UserMailer.account_creation(@user).deliver_later
          flash[:notice] = "Invitation to user #{@user.email} sent."
        else
          flash[:notice] = "User #{@user.email} created."
        end
      else
        render action: "new"
      end
    else
      redirect_to root_path, alert: "Not authorized"
    end
  end

  def show
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User successfully updated' }
      else
        format.html { render action: 'edit'}
      end
    end
  end

  def destroy
    if current_user.admin?
      @user.destroy
      redirect_to users_path , notice: 'User has been deleteted.'
    else
      redirect_to users_path, alert: "Not authorized"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :auth_token, :time_zone)
  end

  def set_user
    @user = if current_user.admin?
              User.find(params[:id])
            else
              current_user
            end
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "email"
  end

  def sort_direction
    %w[asc desc]. include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/views/users/_form.html.haml
= form_for(@user, :html => {:multipart => true, :class => "form-horizontal"}) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :email, :class => "control-label"
    .controls
      = f.text_field :email

  .control-group
    = label_tag :send_invitation, 'Send invitation', class: 'control-label'
    .controls
      = check_box_tag :send_invitation, "1", params[:send_invitation] == '1'
      .help-block Emails an invitation link and allows user to set their own password.

  .control-group
    = f.label :time_zone, class: 'control-label'
    .controls
      = f.time_zone_select :time_zone

  .control-group.password
    = f.label :password, :class => "control-label"
    .controls
      = f.password_field :password

  .control-group.password
    = f.label :password_confirmation, :class => "control-label"
    .controls
      = f.password_field :password_confirmation

  .form-actions
    = f.submit :class => "btn btn-custom-success"

app/views/users/edit.html.haml
%h1 Edit your profile
= render 'form'
= link_to 'Back', users_path, class: "btn btn-custom-back"

app/views/users/index.html.haml
%h1
  Users
  %i.icon-female.icon-large

%table.table.table-striped{"data-provides" => "rowlink"}
  %thead
    %tr
      %th User
      %th= sortable "email"
      %th= sortable "created_at", "Date created"
      %th
      %th
  %tbody
    - @users.each do |user|
      %tr.warning
        %td.number= user.id
        %td.title= link_to user.email, user
        %td.created-at= user.created_at
        %td.nolink.glyph= link_to icon_pencil, edit_user_path(user)
        %td.nolink.glyph= link_to icon_trash, user, method: :delete, data: { confirm: 'Are you sure?' }

= paginate @users

= link_to 'New User', new_user_path, class: 'btn btn-custom-success'

app/views/users/new.html.haml
%h1 Create New User
= render 'form'
= link_to 'Back', users_url, class: "btn btn-custom-back"

app/views/users/show.html.haml
%h1 Profile

.row
  .span3
  .span6.event-description
    %dl.dl-horizontal
      %dt
        %strong Email:
      %dd= @user.email
      %dt
        %strong Time zone:
      %dd= @user.time_zone
  .span3

= link_to 'Edit', edit_user_path(@user), class: "btn btn-custom-success"
= link_to 'Back', users_path, class: "btn btn-custom-back"