config/routes.rb
Rails.application.routes.draw do
  root 'incoming_events#index'

  get "password_resets/new"
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions
  resources :users
  resources :password_resets
  resources :remote_sides

  resources :incoming_events
  resources :expected_events

  resources :alarms do
    get :run, :on => :member
  end

  post '/' => 'incoming_events#create'

end

app/models/expected_event.rb
class ExpectedEvent < ApplicationRecord

  # associations
  #
  #

  belongs_to :remote_side, inverse_of: :expected_events

  has_many :alarm_mappings, dependent: :destroy
  has_many :alarms, through: :alarm_mappings
  has_many :alarm_notifications, dependent: :destroy
  has_many :incoming_events

  # validations
  #
  #

  validates :remote_side, presence: true
  validates :title, presence: true, format: { with: IncomingEvent::FORMAT }
  validates :matching_direction, inclusion: { in: %w(backward forward) }
  validates :day_of_month, numericality: { only_integer: true, within: 1..31, allow_blank: true }
  validates_uniqueness_of :title, scope: :remote_side_id
  validates_inclusion_of :final_hour, in: 0..23
  # TODO not needed for forward matching?
  validate :ensure_either_weekly_or_monthly_is_selected

  # scopes
  #
  #

  scope :active,   -> do
    where(<<-EOFSQL, q: Time.now.utc)
    (started_at < :q AND ended_at > :q)
      OR (started_at < :q AND ended_at IS NULL)
      OR (started_at IS NULL AND ended_at IS NULL)
    EOFSQL
  end
  scope :forward,  -> { where(matching_direction: 'forward') }
  scope :backward, -> { where(matching_direction: 'backward') }
  scope :today,    -> { where("weekday_#{Time.now.utc.wday} = :t OR day_of_month = :d", t: true, d: Time.now.utc.day) }

  # callbacks
  #
  #

  before_validation :delete_white_spaces_from_title

  # instance methods
  #
  #

  def alarm!(incoming_event: IncomingEvent.new)
    alarms.each { |alarm| alarm.with_incoming_event(incoming_event).run self }
    AlarmNotification.create(expected_event: self, remote_side: remote_side)
  end

  def event_matching_direction
    if self.matching_direction == 'forward'
      "when found"
    else
      "when not found"
    end
  end

  def event_matching_direction_for_email
    if self.matching_direction == 'forward'
      "found"
    else
      "not found"
    end
  end

  def active?
    return false if started_at.nil? and ended_at
    return true if started_at.nil? and ended_at.nil?
    started_at.to_time(:utc) < Time.now.utc and (ended_at.nil? || Time.now.utc <= ended_at.to_time(:utc).end_of_day)
  end

  def activity_status
    if active?
      "active"
    else
      "inactive"
    end
  end

  def checked_today?
    weekdays[Time.now.utc.wday]
  end

  def deadline
    if checked_today?
      Time.now.utc.beginning_of_day + final_hour.hours
    elsif monthly?
      DateTime.new(Date.today.year, Date.today.month, day_of_month, final_hour).utc
    else
      Time.now.utc.beginning_of_day
    end
  end

  def deadline_exceeded?
    return false if matching_direction == 'forward'
    Time.now.utc > deadline
  end

  def last_alarm_at
    last_alarm = alarm_notifications.order(:created_at).last
    last_alarm.created_at if last_alarm
  end

  def monthly?
    !!day_of_month && weekdays.none?
  end

  def weekdays
    weekdays = []
    weekdays << !!self.weekday_0 #bang bang, converts nil values into booleans
    weekdays << !!self.weekday_1
    weekdays << !!self.weekday_2
    weekdays << !!self.weekday_3
    weekdays << !!self.weekday_4
    weekdays << !!self.weekday_5
    weekdays << !!self.weekday_6
    weekdays
  end

  def weekly?
    day_of_month.blank?
  end

  private

  def delete_white_spaces_from_title
    self.title = self.title.strip if self.title
  end

  def ensure_either_weekly_or_monthly_is_selected
    unless weekly? ^ monthly?
      errors.add(:base, 'cannot select both day of month and weekday(s)')
    end
  end

end

app/controllers/expected_events_controller.rb
class ExpectedEventsController < ApplicationController

  include SearchFilters

  helper_method :sort_column, :sort_direction
  before_action :set_expected_event, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @expected_event = ExpectedEvent.new(matching_direction: false)
  end

  def edit
  end

  def create
    @expected_event = ExpectedEvent.new(expected_event_params)

    respond_to do |format|
      if @expected_event.save
        format.html { redirect_to @expected_event, notice: 'Expected event was successfully created'}
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @expected_event.update(expected_event_params)
        format.html { redirect_to @expected_event, notice: 'Expected event was successfully updated' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @expected_event.destroy
    respond_to do |format|
      format.html { redirect_to expected_events_url }
    end
  end

  private

  def set_expected_event
    @expected_event = ExpectedEvent.find(params[:id])
  end

  def expected_event_params
    params.require(:expected_event).permit(:title, :weekday_0, :weekday_1, :weekday_2,
      :weekday_3, :weekday_4, :weekday_5, :weekday_6, :day_of_month,
      :matching_direction, :started_at, :ended_at, :date_select,
      :final_hour, :remote_side_id, "alarm_ids" => [])
  end

  def sort_column
    ExpectedEvent.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc]. include?(params[:direction]) ? params[:direction] : "DESC"
  end

end

app/views/expected_events/_form.html.haml
= form_for @expected_event, html: { class: "form-horizontal" } do |f|
  - if @expected_event.errors.any?
    #error_explanation
      %h2
        = pluralize(@expected_event.errors.count, "error")
        prohibited this expected_event from being saved:
      %ul
        - @expected_event.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    %h4 Incoming Event Matching
    .line-separator
    .row
      .span6
        = f.label :title, "Watch incoming event with name:", :class => "control-label"
        .controls
          = f.text_field :title
      .span1
        %h5 OR
      .span5
        %label.control-label{:for => "available_incoming_event_titles"} Choose available
        .controls
          = select_tag :available_incoming_event_titles, options_for_select(IncomingEvent.select('DISTINCT title').order('title').map(&:title)), include_blank: true

  .control-group
    %h4= RemoteSide.model_name.human
    .line-separator
    .control-group
      = f.label :remote_side, "Watch incoming coming from:", :class => "control-label"
      .controls
        = f.select :remote_side_id, RemoteSide.all.map{|site| [site.name, site.id] }, prompt: '<Select One>'

  .control-group
    %h4 Select Frequency
    .line-separator
    .row
      .control-group.span3
        %h5 Weekly
        %button#toggle_weekday_selection Toggle all
    .control-group.weekday-selection
      - 0.upto(6).each do |n|
        %label.checkbox.inline
          = f.check_box "weekday_#{n}"
          = Date::DAYNAMES[n]
    .control-group.span12.explanation
      %em (If no weekdays are checked, the event will be considered inactive)
    .row
      .span3
        %h5 Monthly
        .control-group
          = f.label :day_of_month, class: 'control-label'
          .controls
            = f.select :day_of_month, (1..31), include_blank: true

  .control-group
    %h4 Select Alarms
    .line-separator
    .row
      .span1
      .span5
        .control-group
          = select_tag "expected_event[alarm_ids][]", options_for_select(Alarm.all.map{|a| [a.title, a.id]}, f.object.alarms.map(&:id)), multiple: true

  .control-group
    %h4 Select Notification Type
    .line-separator
    .row
      .span1
      .span5
        .control-group
          %label.radio
            = f.radio_button :matching_direction, 'backward'
            Send an alarm when event is
            %strong not
            found
      .span6
        .control-group
          %label.radio
            = f.radio_button :matching_direction, 'forward'
            Send an alarm when event is found

  .control-group
    %h4 Final Hour
    .line-separator
    .row
      .span6
        .control-group
          = f.label :final_hour, :class => "control-label"
          .controls
            = f.select :final_hour, (1..24)
      .span6.explanation
        .control-group
          %em (Denotes the latest possible hour the event is expected. Only required for backward matching events.)

  .control-group
    %h4 Select Dates
    .line-separator
    .control-group.span6
      = f.label "Start Date", :class => "control-label"
      .controls
        = f.text_field :started_at
    .control-group.span6
      = f.label "End Date", :class => "control-label"
      .controls
        = f.text_field :ended_at

  .form-actions
    = f.submit :class => "btn btn-custom-success pull-right"

app/views/expected_events/edit.html.haml
%h1 Edit Expected Event
= render 'form'
= link_to 'Show', @expected_event, class: "btn btn-custom-show"
= link_to 'Back', expected_events_path, class: "btn btn-custom-back"

app/views/expected_events/index.html.haml
%h1
  Expected Events
  %i.icon-calendar.icon-large
= render 'shared/search_filters'
%p= link_to 'New event expectation', new_expected_event_path , class: 'btn btn-custom-success'
%table.table.table-striped{"data-provides" => "rowlink"}
  %thead
    %tr
      %th Remote
      %th= sortable "title"
      %th= sortable 'final_hour', 'Hour'
      %th Last Alarm
      %th= sortable "matching_direction", "Notify when"
      %th Activity
      %th= sortable 'created_at', 'Created'
      %th
      %th
  %tbody
    - @expected_events.each do |expected_event|
      %tr.success
        %td.nolink= expected_event.remote_side.try(:name)
        %td.title
          %tt= link_to expected_event.title, expected_event
          %br/
          %small
            Weekdays: #{selected_weekdays(expected_event)}
        %td.final-hour= expected_event.final_hour if expected_event.matching_direction == 'backward'
        %td= l expected_event.last_alarm_at, format: :short if expected_event.last_alarm_at
        %td.notification= expected_event.event_matching_direction.gsub('when ', '')
        %td.activity= expected_event.activity_status.titleize
        %td.activity= l expected_event.created_at, format: :short
        %td.nolink.glyph= link_to icon_pencil, edit_expected_event_path(expected_event)
        %td.nolink.glyph= link_to icon_trash, expected_event, method: :delete, data: { confirm: 'Are you sure?' }
= paginate @expected_events

app/views/expected_events/new.html.haml
%h1 New Expected Event
= render 'form'
= link_to 'Back', expected_events_path, class: "btn btn-custom-back"

app/views/expected_events/show.html.haml
.row
  .span1
  .span10.event-description
    %table.table.table-striped
      - if @expected_event.active?
        %tr.success.activity-status
          %td
            %strong
              This event is #{@expected_event.activity_status.titleize}
      - else
        %tr.error.activity-status
          %td
            %strong
              This event is #{@expected_event.activity_status.titleize}
    %table.table.table-striped
      %tr
        %td
          %strong Title:
        %td
          %tt= @expected_event.title
      %tr
        %td
          %strong Selected Weekday(s):
        %td= selected_weekdays(@expected_event)
      %tr
        %td
          %strong Notification:
        %td
          - if @expected_event.matching_direction == 'forward'
            alarm sent when found
          - else
            alarm sent when
            %strong not
            found
      %tr
        %td
          %strong Started at (YY-MM-DD):
        %td= @expected_event.started_at
      %tr
        %td
          %strong Ended at (YY-MM-DD):
        %td= @expected_event.ended_at
      %tr
        %td
          %strong Final Hour:
        %td= @expected_event.final_hour
    %table.table
      %td= link_to "This event has #{@expected_event.alarms.count} Alarms", alarms_path(expected_event_id: @expected_event.id), class: "btn btn-block btn-custom-show"
  .span1
= link_to 'Edit', edit_expected_event_path(@expected_event), class: 'btn btn-custom-success'
= link_to 'Back', expected_events_path, class: "btn btn-custom-back"