config/routes.rb
Rails.application.routes.draw do
  root 'incoming_events#index'

  get "password_resets/new"
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :sessions
  resources :users
  resources :password_resets
  resources :remote_sides

  resources :incoming_events
  resources :expected_events

  resources :alarms do
    get :run, :on => :member
  end

  post '/' => 'incoming_events#create'

end

app/models/remote_side.rb
class RemoteSide < ApplicationRecord

  # associations
  #
  #

  has_many :alarm_notifications, inverse_of: :remote_side, dependent: :nullify
  has_many :expected_events,     inverse_of: :remote_side, dependent: :nullify
  has_many :incoming_events,     inverse_of: :remote_side, dependent: :nullify

  # validations
  #
  #

  validates :name, presence: true
  validates_uniqueness_of :name
  validates_presence_of :api_token

  # callbakcs
  #
  #

  before_validation :generate_api_token, on: :create

  # instance methods
  #
  #

  private

  def generate_api_token
    begin
      self.api_token = SecureRandom.hex
    end while self.class.exists?(api_token: api_token)
  end

end

app/controllers/remote_sides_controller.rb
class RemoteSidesController < ApplicationController

  before_action :set_remote_side, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    @remote_sides = RemoteSide.all.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @remote_side = RemoteSide.new
  end

  def edit
  end

  def create
    @remote_side = RemoteSide.new(remote_side_params)
    respond_to do |format|
      if @remote_side.save
        format.html { redirect_to @remote_side, notice: 'Remote side was successfully created' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @remote_side.update(remote_side_params)
        format.html { redirect_to @remote_side, notice: 'Remote side was successfully updated' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @remote_side.destroy
    respond_to do |format|
      format.html { redirect_to remote_sides_url }
    end
  end

  private

  def set_remote_side
    @remote_side = RemoteSide.find(params[:id])
  end

  def remote_side_params
    params.require(:remote_side).permit([:name, :api_token])
  end

  def sort_column
    RemoteSide.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc]. include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/remote_sides/_form.html.haml
= form_for(@remote_side, :html => {:class => "form-horizontal"}) do |f|
  - if @remote_side.errors.any?
    #error_explanation
      %h2
        = pluralize(@remote_side.errors.count, "error")
        prohibited this remote side from being saved:
      %ul
        - @remote_side.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name, :class => "control-label"
    .controls
      = f.text_field :name

  .form-actions
    = f.submit "Create Remote Side and Generate API Key", :class => "btn btn-custom-success"

app/views/remote_sides/edit.html.haml
%h1
  Edit Remote Side

= render 'form'

= link_to 'Show', remote_side_path(@remote_side), class: 'btn btn-custom-show'
= link_to 'Back', remote_side_path, class: 'btn btn-custom-back'

app/views/remote_sides/index.html.haml
%h1
  Remote Side

%table.table.table-striped{"data-provides" => "rowlink"}
  %thead
    %tr
      %th= sortable "name"
      %th API Token
      %th
      %th

  %tbody
    - @remote_sides.each do |remote_side|
      %tr
        %td.title= link_to remote_side.name, remote_side
        %td.title= remote_side.api_token
        %td.nolink.glyph= link_to icon_pencil, edit_remote_side_path(remote_side)
        %td.nolink.glyph= link_to icon_trash, remote_side, method: :delete, data: { confirm: 'Are you sure?' }

= paginate @remote_sides

= link_to 'New Remote Side', new_remote_side_path(@remote_side) , class: 'btn btn-custom-success'
= link_to 'Back', remote_sides_path , class: 'btn btn-custom-back'

app/views/remote_sides/new.html.haml
%h1
  New Remote Side

= render 'form'

= link_to 'Back', remote_sides_path, class: 'btn btn-custom-back'

app/views/remote_sides/show.html.haml
.row
  .span1
  .span10.event-description
    %table.table.table-striped
      %tr
        %td
          %strong Name:
        %td= @remote_side.name
      %tr
        %td
          %strong API token:
        %td= @remote_side.api_token
  .span1
= link_to 'Edit', edit_remote_side_path(@remote_side), class: "btn btn-custom-success"
= link_to 'Back', remote_sides_path, class: "btn btn-custom-back"